"""Add email verification and password reset fields

Revision ID: aff6962db47c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-21 14:31:49.248980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff6962db47c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_verified column with a server default first to handle existing rows
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    
    # Update existing users to be verified (so they can still login)
    # This is important for backward compatibility
    op.execute('UPDATE users SET is_verified = true WHERE is_verified = false')
    
    # Remove the server default (we want explicit False for new users)
    op.alter_column('users', 'is_verified', server_default=None)
    
    # Add other columns (these are nullable so no issue)
    op.add_column('users', sa.Column('verification_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_otp_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires')
    op.drop_column('users', 'reset_otp')
    op.drop_column('users', 'verification_otp_expires')
    op.drop_column('users', 'verification_otp')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
